### ISSUE TITLE
Product box height on mobile device

### ISSUE THREAD

**Issue by jaszpol** [prestarocket-agence/classic-rocket#159]
Hi i have a little problem with product box height on mobile devices. I have a productcomments module active and title price and product ratting need more space. 

I now code like this will help:
```
@media only screen and (max-width: 400px) {
.product-miniature .card-body{
   height: 165px !important;
}
}
```

But i don't now where put it to be works :/ I want to change size of product box to 165px. Pleas let me know if you now how to do it.

![image](https://user-images.githubusercontent.com/64835152/81980388-cd955780-962e-11ea-91de-6d543b2558a4.png)

**Comment by Hlavtox** [comment]
@jaszpol Do not ever set defined heights of elements. You do not know what will be inside. There could be a problem with fonts that do not load and the text will overflow outside. Send me the URL of the page and I will have a look on it.

**Comment by jaszpol** [comment]
https://www.sklep.gameskingdom.pl

**Comment by Hlavtox** [comment]
@jaszpol Legal compliance CSS is fucking with it.

Add this to your custom.css file: 

```
body.tax-display-enabled .featured-products .product-description {
  height: auto;
}
```

**Comment by jaszpol** [comment]
it's works thank you :))
