### ISSUE TITLE
Serious issues on Internet Explorer and Edge

### ISSUE THREAD

**Issue by dangelion** [prestarocket-agence/classic-rocket#162]
On **IE 11** in console you get error: 

`SCRIPT1002` (it's a syntax error on bottom-xxxxx.js)

On **Edge** you get:

`SCRIPT1028: Expected identifier, string or number`

In both cases it blocks the JS execution and the website is broken.

You can check these errors on your demo online.

Lot of results and solutions [googling it](https://www.google.com/search?q=script1028+expected+identifier+string+or+number&oq=script1028+)
Maybe the [fastest one](https://stackoverflow.com/a/61889894/1252920) would be adding Babel to translate the code to **ES5** syntax (?)

Very serious issues, is it possible to solve them asap? Thanks

**Comment by prestarocket** [comment]
I figured it out, and I hate webpack.

**Comment by dangelion** [comment]
@prestarocket have you in plan to solve this soon? It's a huge problem for my client...

**Comment by prestarocket** [comment]
@dangelion i have to create a release but it s fix here : https://github.com/prestarocket-agence/classic-rocket/issues/162

**Comment by matks** [comment]
> I figured it out, and I hate webpack.

You're not alone https://twitter.com/STuFFk/status/1270431858703073280?s=19
