### ISSUE TITLE
wrong width add to cart button 

### ISSUE THREAD

**Issue by eligomez86** [prestarocket-agence/classic-rocket#163]
Hi!

In the two last versions of Classic Rocket I'm having an important problem:

The width of the add to cart button in product page makes square all the product page (on mobile version)

It seems it size were more than 100% but I do not know how to fix it.

Anybody could help me?

thanks

**Comment by eligomez86** [comment]
![Screenshot_20200608_181257_com android chrome](https://user-images.githubusercontent.com/66635779/84055033-8a6f9f80-a9b4-11ea-96f4-c002029a1572.jpg)

**Comment by prestarocket** [comment]
could you give the url of your shop plz ?

**Comment by eligomez86** [comment]
https://productosesotericoscm.com/tienda/

**Comment by prestarocket** [comment]
in themes/classic-rocket/templates/catalog/_partials/product-add-to-cart.tpl replace "add col" with "add col-auto"
i will publish a release tomorow

**Comment by eligomez86** [comment]
Thank you very much! It works fine!
