### ISSUE TITLE
npm build/watch

### ISSUE THREAD

**Issue by nektart** [prestarocket-agence/classic-rocket#203]
On compilation of the css file, I have an error with the _fonts.scss
I use Node js last version with npm too.
It doesn't recognize the 4 fonts links (~material-design-icons/iconfont/MaterialIcons-Regular.eot)
It works if I desactivate the _fonts.scss file from the theme.scss

Have u some idea ?

Thanks in advance

**Comment by prestarocket** [comment]
maybe npm install material-icons in _dev folder.
we will drop material icon for boostrap icon
