### ISSUE TITLE
New account page

### ISSUE THREAD

**Issue by prestarocket** [prestarocket-agence/classic-rocket#204]
![Account-home](https://user-images.githubusercontent.com/899422/101807877-ea870000-3b15-11eb-90d3-40da7777eafa.png)

**Comment by Nice1980-droid** [comment]
Hello,

Do you have a release date for v2 ?

Thank you

**Comment by prestarocket** [comment]
in 2/3 weeks

**Comment by cnbjornsen** [comment]
@prestarocket How is everything coming together? Is there anything I can do to help? Test the beta etc.
Sorry for being impatient. I have a project in the pipeline for which I would like to use Presta Rocket V2. :-)

**Comment by prestarocket** [comment]
> @prestarocket How is everything coming together? Is there anything I can do to help? Test the beta etc.
> Sorry for being impatient. I have a project in the pipeline for which I would like to use Presta Rocket V2. :-)

https://github.com/prestarocket-agence/classic-rocket/tree/release/4.0.0-beta.001
