### ISSUE TITLE
New add to cart offcanvas

### ISSUE THREAD

**Issue by prestarocket** [prestarocket-agence/classic-rocket#205]
![Boutique - Offcanvas-add-to-cart](https://user-images.githubusercontent.com/899422/101808067-25893380-3b16-11eb-853b-6ae1c666f21d.png)
 live example on https://www.foot.fr/

**Comment by chbj** [comment]
@prestarocket I am not aware of the behavior in the actual version, but on foot.fr I am missing the option to see the off-canvas cart again, for instance when clicking the cart icon.

I am also missing the option to remove an item from the cart, without visiting the cart page.
