### ISSUE TITLE
jpg extension support is missing

### ISSUE THREAD

**Issue by dali-rajab** [prestarocket-agence/classic-rocket#212]
Hello !
I think we should modify this line, because it's not supporting jpg extensions, => jpe?g (optionnal e) :

![npm_jpg](https://user-images.githubusercontent.com/39015823/105847164-880e9400-5fdd-11eb-818f-9dc4c536ae0e.jpg)

https://github.com/prestarocket-agence/classic-rocket/blob/4dad8fcbc30a25b3963ae5b9e3fb3790dac9a563/_dev/webpack.config.js#L103

to become : 
```js
test: /\.(png|jpe?g|gif|svg|webp)$/, 
```

I tested and it works

**Comment by tswfi** [comment]
Thanks!

There are no jpg or jpeg files in the theme but as this is also used as a base for child themes its probably good to fix this to show an example :)

Opened pr to fix this: https://github.com/prestarocket-agence/classic-rocket/pull/225
