### ISSUE TITLE
Extra line

### ISSUE THREAD

**Issue by dali-rajab** [prestarocket-agence/classic-rocket#213]
Hello friends !

I think this is a forgotten line by some one :
https://github.com/prestarocket-agence/classic-rocket/blob/4dad8fcbc30a25b3963ae5b9e3fb3790dac9a563/_dev/js/theme.js#L65

**Comment by tswfi** [comment]
I'm not the maintainer but I use this theme a lot and decided to use the evening to do some housekeeping :)

Thanks for your report, no idea why that is there. It was added in this pr: https://github.com/prestarocket-agence/classic-rocket/issues/162

I opened a pr to remove it: https://github.com/prestarocket-agence/classic-rocket/pull/224
