### ISSUE TITLE
Prestashop productcomments has switched to returning JSON

### ISSUE THREAD

**Issue by tswfi** [prestarocket-agence/classic-rocket#216]
see: https://github.com/PrestaShop/productcomments/pull/81        
especially this commit: 
https://github.com/PrestaShop/productcomments/pull/81/commits/9e019037c49e1288ddeb54783d56ffd14e7ec4ac

the override in classic-rocket tries to parse the already json format which fails with

```
Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.success (list-comments.js:56)
    at u (core.js:39)
    at Object.fireWith [as resolveWith] (core.js:39)
    at S (core.js:39)
    at XMLHttpRequest.<anonymous> (core.js:39)
```

there are few places in list-comments that try to parse the response: https://github.com/prestarocket-agence/classic-rocket/blob/646572802860b9fe49506f01c66af0d035cb916f/modules/productcomments/views/js/list-comments.js#L56

This probably needs to be fixed in a way that both the old and new format can be supported.

**Comment by Culvanen** [comment]
I have the same problem, how to solve it ?

**Comment by tswfi** [comment]
There is a pr, but it is still under review https://github.com/prestarocket-agence/classic-rocket/pull/220
