### ISSUE TITLE
Sort order listing not working

### ISSUE THREAD

**Issue by valentin-anamorphik** [prestarocket-agence/classic-rocket#218]
Hi,

On product list, select order not working.

```
# src/js/listing.js
$('body').on('change','#select-sort-order', function () {
  var urlsearch = $(this).val();
  prestashop.emit('updateFacets',urlsearch);
});
```

![image](https://user-images.githubusercontent.com/32865180/109285410-5594c880-7821-11eb-9184-bfe4a031571a.png)

Thanks.

**Comment by tswfi** [comment]
I cannot replicate this.

Please provide some more information: Prestashop version? Theme version? Any errors in js console?

If you have a public test environment I could check that would help also.
