### ISSUE TITLE
Noindex in category page

### ISSUE THREAD

**Issue by grzegorzgit** [prestarocket-agence/classic-rocket#233]
I have just noticed that google has blocked plenty of our pages because they have "noindex". I was shocked, but you put into the header <meta name="robots" content="none">. Why would you do this?  You also don't put any explaination why is it there.

It is file /templates/_partials/head.tpl line 45.

What does it mean {* if listing is sort or with facet *}"?

**Comment by prestarocket** [comment]
page sorted : https://crv2.prestarocket.com/3-vetements?order=product.name.asc
page with facet : https://crv2.prestarocket.com/3-vetements?q=Cat%C3%A9gories-Femmes

noindex is use for duplicate content
