### ISSUE TITLE
Partial use of the new image sizes

### ISSUE THREAD

**Issue by lmeyer1** [prestarocket-agence/classic-rocket#234]
Classic-rocket introduces new image sizes (pdt-180, pdt-300, etc.), but it still uses the native prestashop sizes (small_default, medium_default). As far as I understand, to really take advantage of the change, the new sizes should be used everywhere. Is there a rationale behind the fact that both types of sizes are used, or is this only due to partial implementation?

I would like to go a step further and replace the native prestashop sizes with the newly introduced sizes. What are your thoughts about this?

**Comment by prestarocket** [comment]
some modules use default image sizes; 
you can remove sizes if you are sure that a third module does not need them
