### ISSUE TITLE
Registration form bug, needs immediate fix

### ISSUE THREAD

**Issue by grzegorzgit** [prestarocket-agence/classic-rocket#239]
Hi,
I have just found out that new customers cannot register, and it's because of invalid address form.

If you fill the address form (in checkout, as a new customer), but you skip one required field, the form is submitted but come back with an error. After this submit (and new page load) the submit button is no longer active, and filling out the missing required field doesn't make the button active again.

So basically if you fill out the address form, but you forget to fill one required field, you will be stacked with that page and not able to go further.

Refreshing page sometimes helps and activate the button. My guess is that in JS validation, there is missing something that checks if the required field was filled and makes the submit button active.

Please consider fixing this immediately, it is a serious problem.

**Comment by grzegorzgit** [comment]
The zip, from here [https://github.com/prestarocket-agence/classic-rocket](https://github.com/prestarocket-agence/classic-rocket)

**Comment by lmeyer1** [comment]
I'm using develop branch, and I cannot reproduce, neither on registration nor on address form.

**Comment by grzegorzgit** [comment]
Ok, I am glad that it works on dev :D but the link that people download the theme, the official version is broken. Commenting out validation in form.js  fixes the problem (form.js:58).

**Comment by IJVo** [comment]
Dev does not work on PrestShop 1.7.7.3 and 1.7.7.4 :-(

**Comment by lmeyer1** [comment]
@IJVo 
> Dev does not work on PrestaShop 1.7.7.3 and 1.7.7.4

What problem do you have? With me it works, but for productcomments and blockwishlist. I'm working on fixing both. See PR #237, #238 and #241

**Comment by prestarocket** [comment]
fix in https://github.com/prestarocket-agence/classic-rocket/releases/tag/3.1.0
