### ISSUE TITLE
Beta - mobile navigation not toggleable

### ISSUE THREAD

**Issue by 0dp** [prestarocket-agence/classic-rocket#245]
I've just checked out the beta demo on my Android with chrome.
Looks like the mobile navigation is untoggleable.

**Comment by prestarocket** [comment]
i know, module menu is not ready yet

**Comment by 0dp** [comment]
@prestarocket 
I don't see that mentioned anywhere.
Maybe a roadmap, project milestones or similar would be helpful for beta testers and contributors?
