### ISSUE TITLE
A suggestion for Largest Contentful Paint in mobile

### ISSUE THREAD

**Issue by thomas298** [prestarocket-agence/classic-rocket#304]
Hello, thanks to everyone for the work that they put on this theme.
Just a question/suggestion from someone who lacks a lot in knowledge.
The photo of the first product in the section popular products is the Largest Contentful Paint when we are in mobile.
Should it be lazyloaded or another way would be better?
Thank you for your time.

**Comment by prestarocket** [comment]
Not lazyloaded but preloaded

**Comment by thomas298** [comment]
My bad, sorry and thanks
