### ISSUE TITLE
Category block display

### ISSUE THREAD

**Issue by Hlavtox** [prestarocket-agence/classic-rocket#78]
- Category arrows are not aligned with the title
- Plus sign doesnt change to minus when clicking the category title

Prestashop version: 1.7.6

![left category](https://user-images.githubusercontent.com/6097524/62292777-7c352680-b467-11e9-8993-14b9f0b78d1e.JPG)

**Comment by Astralabe** [comment]
in my shop with PrestaShop: 1.7.8.3 and Classic Rocket version: 3.1.0

The category arrows are now aligned with the title but the plus sign still doesn't change to minus when you click on the category title.
<img width="214" alt="Capture d’écran 2022-02-13 143058" src="https://user-images.githubusercontent.com/99598498/153755600-44235866-5a6f-4028-9411-b7031af8ea2a.png">
