### ISSUE TITLE
Faceted search OK button bad display on iPhone XS

### ISSUE THREAD

**Issue by Hlavtox** [prestarocket-agence/classic-rocket#91]
The OK button to confirm selected filters is squished on iPhone XS and others.

**Additional info**
classic-rocket develop
Prestashop 1.7.6
Faceted search 3.2.1

**Image**
![IMG_6745](https://user-images.githubusercontent.com/6097524/64655839-ced20d00-d42d-11e9-8853-8990e43914c7.PNG)

**Comment by Hlavtox** [comment]
I dont know how to solve it, no matter what padding you put there, Safari will cut it off it seems.

If you try it on other phones or on desktop in dev responsive mode, it looks OK.

**Comment by micka-fdz** [comment]
Maybe with `-webkit-appearance: none;` to prevent Safari from styling form elements.

**Comment by Hlavtox** [comment]
@prestarocket Found out it's general safari behaviour. It shrinks due to flex layout of the offcanvas modal.

This fixes it:

```
	#offcanvas_search_filter .modal-footer,
	#offcanvas_search_filter .modal-footer {
		flex-shrink: 0;
	}
```

To which CSS should I make a PR?
