### ISSUE TITLE
Image slider changes to last slide on orientation change

### ISSUE THREAD

**Issue by Hlavtox** [prestarocket-agence/classic-rocket#92]
1. Add 2 or more images to a product.
2. Open the product in front office.
3. Use mobile device or dev mode on desktop.
4. Change orientation or resize the window.
5. Slick slider changes to (I think) the last photo and looses sync.

**Additional info**
classic-rocket develop
Prestashop 1.7.6
Faceted search 3.2.1

**Video**
https://drive.google.com/file/d/1Jqj6SdJX-drjF0oAeaOFZUjyxfhdTcRi/view?usp=sharing

**Comment by etsmes** [comment]
Please, have you found any solution to this problem?

**Comment by prestarocket** [comment]
try thhis in custom.js :
`$(window).on("orientationchange",function(){
    $(window).one('resize', function() {
    $('[data-slick]').slick('reinit');
    });

});`
